Complete SSH deployment configuration

diff --git a/.github/workflows/deploy-main.yml b/.github/workflows/deploy-main.yml
--- a/.github/workflows/deploy-main.yml
+++ b/.github/workflows/deploy-main.yml
@@ -19,36 +19,26 @@ jobs:
           host: ${{ secrets.SSH_MAIN_HOST_IP }}
           port: 22
           username: ubuntu
-          key: ${{ secrets.SSH_MAIN_PRIVATE_KEY }}
+          key: ${{ secrets.SSH_MAIN_PRIVATE_KEY }} 
           script: |
-            whoami
-            hostname  
+            cd /home/github_user/workspace/mini-rag
+            git checkout main
+            git pull
+            sudo systemctl restart minirag.service
+            echo "Wating..."
+            sleep 20
 
-      # - name: Deploy via SSH
-      #   uses: appleboy/ssh-action@v1.2.2
-      #   with:
-      #     host: ${{ secrets.SSH_MAIN_HOST_IP }}
-      #     username: ubuntu
-      #     key: ${{ secrets.SSH_MAIN_PRIVATE_KEY }} 
-      #     script: |
-      #       cd /home/github_user/workspace/mini-rag
-      #       git checkout main
-      #       git pull
-      #       sudo systemctl restart minirag.service
-      #       echo "Wating..."
-      #       sleep 20
+            for i in {1..6}; do
+              if ss -tuln | grep -q ':80'; then
+                  echo "✅ Port 80 is now active."
+                  break
+              else
+                  echo "⏳ Port 80 not ready yet. Retrying in 5 seconds..."
+                  sleep 5
+              fi
+            done
 
-      #       for i in {1..6}; do
-      #         if ss -tuln | grep -q ':80'; then
-      #             echo "✅ Port 80 is now active."
-      #             break
-      #         else
-      #             echo "⏳ Port 80 not ready yet. Retrying in 5 seconds..."
-      #             sleep 5
-      #         fi
-      #       done
-
-      #       if ! ss -tuln | grep -q ':80'; then
-      #           echo "❌ Service failed to start on port 80"
-      #           exit 1
-      #       fi
+            if ! ss -tuln | grep -q ':80'; then
+                echo "❌ Service failed to start on port 80"
+                exit 1
+            fi
